### ISSUE TITLE
Do we want to edit the proposal in an implementation-neutral approach?

### ISSUE THREAD

**Issue by tQsW** [youennf/mdns-ice-candidates#1]
> The second approach implemented in the WebKit engine enforces the following policy

Not sure if it would be ideal to motivate the work in an implementation-neutral way, though I cannot think of a better approach at this moment. That said, should we also mention the current practice in Blink? I think the behavior is different but the same dilemma arises.

>   Private browsing mode contexts usually do not share any information with regular browsing contexts.

Is *context* a WebKit terminology? Do we want to also relate the definition of contexts to *origins*?

**Comment by juberti** [comment]
Yes, I think we should avoid mentioning implementation specifics in this document.

**Comment by youennf** [comment]
Filed https://github.com/youennf/mdns-ice-candidates/pull/12
@tQsW, can you take a look?

**Comment by tQsW** [comment]
> Filed #12

This PR looks good to me.
