### ISSUE TITLE
Is the number of mDNS candidates a fingerprinting surface?

### ISSUE THREAD

**Issue by juberti** [youennf/mdns-ice-candidates#21]
Original text:
> The number of mDNS hostname candidates can provide a fingerprinting dimension. If so desired an ICE agent MAY expose additional mDNS hostname candidates that are not registered.

I'm not sure this provides an actual new fingerprinting surface - assuming the interface is in fact exposed to the outside world, a srflx candidate will also be generated for each mDNS candidate - and in the mode we are most concerned about, Mode 2, there will either be 1 or 2 mDNS candidates.

**Comment by jeroendeb** [comment]
If we decide that this draft only applies to mode 2 or default routes, I agree that there is no fingerprinting surface. However, that assumption hasn't been called out anywhere in this doc AFAIK.

**Comment by juberti** [comment]
We still get a srflx and TURN candidate for each interface though.

**Comment by jeroendeb** [comment]
Ok, good point. I agree, we should remove that paragraph. I'll create a PR

**Comment by youennf** [comment]
If an interface cannot connect to a STUN server, there will be no srflx candidate.
I don’t think we can assume that such interface will also not support multicast.

**Comment by juberti** [comment]
Right, as noted in the OP, but this seems like an edge case.

**Comment by youennf** [comment]
I think it is better to mention an issue even though this is an edge case.
Something like:
If there are multiple host candidates with different IP addresses, IPv4 and/or IPv6, each results in a separate mDNS hostname candidate. The number of mDNS hostname candidates might provide a fingerprinting dimension. This is in particular the case for network interfaces whose existence are not exposed through other means like provided STUN servers. No new information is provided when exposing default route candidates.

**Comment by youennf** [comment]
Filed https://github.com/youennf/mdns-ice-candidates/pull/55 to follow up on that.
