### ISSUE TITLE
Don't pair mDNS candidates with relay candidates

### ISSUE THREAD

**Issue by juberti** [youennf/mdns-ice-candidates#29]
If we resolve a name N1 to 1.1.1.1, should we pair it with relay candidates? If we do so, 1.1.1.1 will be sent to the TURN server, which seems like a leak (could be under the control of the web app).

Probably need to add a section in the privacy considerations saying any remote mdns candidates MUST NOT be paired with local relay candidates (although the reverse should be OK).

**Comment by tQsW** [comment]
> any remote mdns candidates MUST NOT be paired with local relay candidates

I am thinking about the impact on the connectivity, and if we can ever resolve the remote mdns candidate, the chance of selecting relay<->mdns even if this is allowed could probably be low if the local side also gathers a host candidate. The MUST level lgtm.

**Comment by juberti** [comment]
yeah, and keep in mind that usually these host IPs will be things like 192.168.1.3 that are not even reachable by the outside world.

**Comment by juberti** [comment]
yeah - we already throw away private IPs for TURN to avoid creating connections that won't work, so the actual impact here is negligible.
