### ISSUE TITLE
Fix examples for HTML I-D

### ISSUE THREAD

**Issue by juberti** [youennf/mdns-ice-candidates#33]
Not sure what needs to be done here, but would be nice to fix

**Comment by tQsW** [comment]
The rendered html (from the link in "Latest version available here") looks similar to the rendered markdown. Are you referring to a different issue?

**Comment by juberti** [comment]
The main issue now is that the examples have a scrollbar. May just need to reduce the width a bit more.

**Comment by youennf** [comment]
Fixed in https://github.com/martinthomson/i-d-template/issues/167

**Comment by juberti** [comment]
Fixed by #58
