### ISSUE TITLE
HTML generator adds "Section" to markdown section links

### ISSUE THREAD

**Issue by tQsW** [youennf/mdns-ice-candidates#36]
E.g. "Step 5 in Section {{gathering}}" in .md becomes "Step 5 in Section *Section 2.1*" in .html or "Step 5 in Section <a href="#gathering" class="xref">Section 2.1</a>" in the raw html source.

**Comment by juberti** [comment]
Was this fixed?

**Comment by tQsW** [comment]
No, it looks to me an issue with the generator code. Or, can I fix it inline? I was assuming the html would be auto-generated,  but if it is supposed to just upload a copy, I will fix it inline asap.

**Comment by tQsW** [comment]
I was wrong. This issue is gone in the newly generated HTML.

**Comment by juberti** [comment]
OK, will do as part of the upload

**Comment by juberti** [comment]
Resolved in latest HTML.
