### ISSUE TITLE
Study the impact of exposing well-known mDNS services to STUN

### ISSUE THREAD

**Issue by youennf** [youennf/mdns-ice-candidates#37]
As pointed by @alvestrand, one can stuff ICE candidates with mDNS names that are not UUID.
This may ease exposing some devices (MyPreferredTV.local) to some unsolicited mDNS/STUN traffic.

**Comment by youennf** [comment]
To be noted that a web application can currently synthesize candidates with well-known IP addresses/address ranges.
Allowing non UUID mDNS resolution might ease such attacks.

We should evaluate whether this is fine as is or not.
One possibility would be to mandate mDNS resolution for UUID-based names only.

**Comment by youennf** [comment]
Implementations might use the same code path for mDNS and unicast DNS, so I am not sure this will be easy to do this distinction in practice.

I would do the distinction between applications that trust the source of ICE candidates (in which case any mDNS is fine) from cases where there is no trust (web browsers typically). In the latter case, I would go with a SHOULD statement.

**Comment by youennf** [comment]
Started PR https://github.com/youennf/mdns-ice-candidates/pull/65

**Comment by juberti** [comment]
Fixed via #65
