### ISSUE TITLE
Spec requirement for new modes

### ISSUE THREAD

**Issue by tQsW** [youennf/mdns-ice-candidates#4]
> Specification Requirements

We may need to add a request for the definition of new modes in a different spec.

**Comment by youennf** [comment]
Sounds good, we might want to flesh out what we are after there.
If we want to expose multiple interfaces, the use case that seems most promising to me is Wifi+VPN so that direct WiFi connections could happen.
Or do you have other cases in mind?

**Comment by juberti** [comment]
Per the discussion at IETF 102, the potential modes include:
2.1 Mode 2, but with private IPv4/non-temporary IPv6 hidden by mDNS
2.2 Mode 2, but with private IPv4/v6s hidden by mDNS

I would also suggest that we suggest 2.1/2.2 as the new default for when no consent has been provided.

**Comment by lgrahl** [comment]
I guess this is the issue where we should discuss the impact on applications that do not (or cannot) obtain consent.

**Comment by juberti** [comment]
@lgrahl, we should simply discuss the implications versus Mode 2.

**Comment by juberti** [comment]
See also discussion in #8 regarding where modes should be defined.

**Comment by juberti** [comment]
Closing in favor of #8
