### ISSUE TITLE
Reference needed to RFC2119

### ISSUE THREAD

**Issue by jeroendeb** [youennf/mdns-ice-candidates#42]
The document seems to lack a both a reference to RFC 2119 and the recommended RFC 2119 boilerplate, even if it appears to use RFC 2119 keywords.

**Comment by juberti** [comment]
Indeed. Probably just need a Section 2 that says

       The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL
       NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and
       "OPTIONAL" in this document are to be interpreted as described in {{RFC2119}}.

**Comment by juberti** [comment]
Fixed by #47
