### ISSUE TITLE
Pages should not be allowed to trigger massive amounts of MDNS traffic

### ISSUE THREAD

**Issue by youennf** [youennf/mdns-ice-candidates#5]
This was pointed by Cullen in https://mailarchive.ietf.org/arch/msg/rtcweb/zGbK1yPaLY5ZBij6tzYykkDC_js

The spec should probably mention the risk and the possibility to throttle MDNS resolution queries.

**Comment by juberti** [comment]
yeah, we should have a Security Considerations section that includes this.
