### ISSUE TITLE
Abstract contains a reference 

### ISSUE THREAD

**Issue by jeroendeb** [youennf/mdns-ice-candidates#50]
From the 'nits' link on top of the IETF submitted version.

** The abstract seems to contain references ([RFC6762]), which it
     shouldn't.  Please replace those with straight textual mentions of the
     documents in question.

**Comment by juberti** [comment]
Probably can just move the ref to the intro section.

**Comment by youennf** [comment]
https://github.com/youennf/mdns-ice-candidates/pull/56
