### ISSUE TITLE
Multiple IP addresses in an mDNS response

### ISSUE THREAD

**Issue by jeroendeb** [youennf/mdns-ice-candidates#7]
It is conceivable that a server would implement ICE with mDNS candidates.

There should be nothing in the ICE candidate processing that prevents this from working. Therefore we should call out what should happen when an mDNS query returns multiple IP addresses. E.g. use the 'best' on (where IPv6 is better than IPv4)?

**Comment by juberti** [comment]
This is a complex area. A simpler option could be that we mandate 1:1 for mDNS, and/or pick the first address of the expected type.

**Comment by youennf** [comment]
Mandating 1:1 for mDNS in the context of WebRTC is probably the straightforward approach. We should probably also define the behavior in the case of multiple responses, picking the first record makes sense to me.

This requirement causes a potential issue when using MDNS for non default route though: it creates a fingerprinting vector by counting the number of different MDNS names for a given peer connection.

I am not sure what reliable means we have to know the expected type of the address and whether this is a requirement at all. The easy solution would be to include this information in the MDNS name.

**Comment by juberti** [comment]
Good point about type not being known a priori, and we could put a hint in the name.
Another option could be to resolve the name before forming pairs, take the first record found, and then only pair the resolved address with local candidates of the appropriate family.

**Comment by jeroendeb** [comment]
> 
> This requirement causes a potential issue when using MDNS for non default route though: it creates a fingerprinting vector by counting the number of different MDNS names for a given peer connection.
> 
An ICE agent concerned about this could potentially signal a random number of additional fake mDNS candidates (unregistered mDNS names).

**Comment by juberti** [comment]
Fixed by #14
