### ISSUE TITLE
Pick a single term for the mDNS behavior

### ISSUE THREAD

**Issue by juberti** [youennf/mdns-ice-candidates#77]
Does it obfuscate, conceal, or obscure local IP addresses?

My vote is for *conceal*.

**Comment by tQsW** [comment]
Conceal/concealment sgtm.

**Comment by juberti** [comment]
As noted in #79, we don't need to use the same term in every case, but the terms should have the same meaning. conceal and hide are fairly synonymous, but conceal and obfuscate have slightly different meanings.
